### ISSUE TITLE
Kilowatt-W

### ISSUE THREAD

**Issue by Kilowatt-W** [FrodoVDR/tasmota-ccu#1]
In der aktuellen Version 0.18 hab ich einen kleinen Fehler gefunden in Verbindung mit Multi-Relay Devices und Tasmota :

Beginnend mit Zeile 288 :

URL2="http://${IPADDR}/cm?user=${USER}&password=${PASSWD}&cmnd=Power"

gehört ersetzt mit :

URL2="http://${IPADDR}/cm?user=${USER}&password=${PASSWD}&cmnd=Power${RELNR}"

Dann klappt die Statusabfrage wunderbar mit mehreren Relays, sonst ist die Rückmeldung immer der Status von P1 :-)

Danke für deine Arbeit, ist wirklich unersetzlich geworden

Gruß aus Österreich

Kilowatt

**Comment by FrodoVDR** [comment]
Fixed
